<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NZ.HRM.Domain\NZ.HRM.Domain.csproj" />
    <ProjectReference Include="..\NZ.HRM.Application\NZ.HRM.Application.csproj" />
    <ProjectReference Include="..\NZ.Leave.Domain\NZ.Leave.Domain.csproj" />
    <ProjectReference Include="..\NZ.Leave.Application\NZ.Leave.Application.csproj" />
    <ProjectReference Include="..\NZ.Shared.Contracts\NZ.Shared.Contracts.csproj" />
    <ProjectReference Include="..\NZ.Shared.Events\NZ.Shared.Events.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
