<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NZ.Leave.Domain\NZ.Leave.Domain.csproj" />
    <ProjectReference Include="..\NZ.Shared.Contracts\NZ.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
