<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NZ.HRM.Application\NZ.HRM.Application.csproj" />
    <ProjectReference Include="..\NZ.Payroll.Domain\NZ.Payroll.Domain.csproj" />
    <ProjectReference Include="..\NZ.HRM.Domain\NZ.HRM.Domain.csproj" />
    <ProjectReference Include="..\NZ.Shared.Contracts\NZ.Shared.Contracts.csproj" />
    <ProjectReference Include="..\NZ.Shared.Events\NZ.Shared.Events.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
