<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NZ.HRM.Utility\NZ.HRM.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Employees\Query\" />
  </ItemGroup>

</Project>
