<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NZ.HRM.Application.Model\NZ.HRM.Application.Model.csproj" />
    <ProjectReference Include="..\NZ.HRM.Domain\NZ.HRM.Domain.csproj" />
    <ProjectReference Include="..\NZ.HRM.Mapping\NZ.HRM.Mapping.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Menus\Queries\" />
    <Folder Include="Menus\Commands\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
